### ISSUE TITLE
Search trace user friendliness

### ISSUE THREAD

**Issue by spaaaacccee** [ShortestPathLab/posthoc-app#28]
Currently, it can be quite a struggle to write a valid search trace and visualise it. This is due to the following reasons:
- No validation when writing traces - no immediate prompt to tell the user the format is wrong
- Inadequate error handling - when a broken search trace is loaded, the most common response is a cryptic error message in the console and a loading bar that never stops.

**Proposals**

- Improve documentation on the search trace, with both examples and API references
- Slightly improve search trace structure for legibility (less nested structures)
- Introduce JSON schema for the search trace (may be automatically generated
- Use a validator (zod) for the parser
- Introduce more error boundaries in the parser

**Comment by Spaaaacccee** [comment]
In [28d4b97](https://github.com/path-visualiser/app/commit/28d4b97c8a2fb70fd1be3b14614e89a70d208324), we introduce basic error messages and error state.
<img width="329" alt="image" src="https://github.com/path-visualiser/app/assets/15244945/d7d66177-e892-40b0-8831-2c995d843f9e">
<img width="257" alt="image" src="https://github.com/path-visualiser/app/assets/15244945/25f5e54e-03bf-409b-8935-bf08c2363db3">

**Comment by Spaaaacccee** [comment]
Proposal for v1.1.0 search trace
```yaml
version: 1.1.0

components:
  tile:
  - $: rect
    width: 1
    height: 1
    x: ${{ event.x + i }}
    y: ${{ event.y }}
    fill: ${{ color[event.type] }}
    text: i = ${{ i }}
    textX: 0.1
    textY: 0.9
    fontSize: 0.35
    fontColor: ${{ themeBackground }}
    $for:
      $to: 10 # Optional, default 1
      $step: 2 # Optional, default 1

views:
  main:
  - $: tile

events:
- type: source
  id: 1736
  x: 8
  y: 15

```

Notably, variables are denoted with ${{}} like github actions to eliminate necessecity for string quotes "". The format is less nested to make it easier to out from solvers.

**Comment by Spaaaacccee** [comment]
To be in line with the version number for the release of Posthoc, this iteration of the search trace will have the version number v2.0.0

```yaml
version: 2.0.0

render:
  main: # Main component
    - $: rect # Introduce defaults for most variables, like width, height = 1 (need LSP to help with visibility/discoverability)
      x: ${{ x }}
      y: ${{ y }}
      fill: ${{ palette[type] }}
  grid:
    - $: grid
      a: ${{ x }}
      b: ${{ y }}

pivot: # Per event pivot (might be different from simply x and y)
  x: ${{ x + 0.5 }}
  y: ${{ y + 0.5 }}
  scale: 0.75

events:
# Allow specification of component (optional)
  - { $: grid, type: expanding, id: 1736, x: 8, y: 15, f: 0.2, g: 22 } # Optional flow style
  - { type: generating, id: 1736, x: 8, y: 15, f: 0.2, g: 22 } # Optional flow style
```
